package com.continentgen.world;

import com.continentgen.map.ClimateZone;
import com.continentgen.map.MapData;
import com.continentgen.map.MapLoader;
import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryOps;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.util.Identifier;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.source.BiomeSource;
import net.minecraft.world.biome.source.util.MultiNoiseUtil;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;
import java.util.stream.Stream;

/**
 * Custom BiomeSource that selects biomes based on the 7 PNG maps.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WORLD SIZE — PER-INSTANCE (NOT SHARED):
 *   Each ContinentBiomeSource holds its OWN worldSize field (decoded from
 *   the codec / preset JSON). MapData does NOT store worldSize — it is
 *   passed as a parameter to every query method. This fixes the critical
 *   bug where multiple ContinentBiomeSource instances (one per preset
 *   during registry loading) all called setWorldSize() on the shared
 *   singleton MapData, and the LAST one constructed would overwrite the
 *   others.
 *
 * CODEC DESIGN:
 *   RegistryOps.getEntryLookupCodec(RegistryKeys.BIOME) returns a
 *   RecordCodecBuilder (NOT a MapCodec), so .forGetter(...) does NOT exist
 *   on it. It is passed directly into instance.group(...) — the value comes
 *   from RegistryOps (dimension's dynamic biome registry), not from the
 *   object. This is the vanilla MultiNoiseBiomeSource pattern.
 *
 *   The codec accepts a "world_size" field (default 300000) which is
 *   passed to the constructor and stored on the instance.
 *
 * BIOME-RESOLUTION COORDINATES (CRITICAL FIX #1):
 *   In MC 1.18+, BiomeSource.getBiome(int x, int y, int z, sampler) is
 *   called with QUART-RESOLUTION coordinates — 1 unit = 4 blocks
 *   horizontally AND vertically. The vanilla BiomeAccess passes
 *   pos.getX() >> 2 into getBiome. Our previous code treated these as
 *   block coordinates, which made every biome sample land at 1/4 of the
 *   actual world position. The visible symptoms were:
 *     • Biomes didn't match the climate shown in F3 (climate used the
 *       player's block position, biome used 1/4 of it).
 *     • Biome zones appeared ~4× smaller than they should be.
 *     • Bizarre overlaps between climate zones and biomes.
 *
 *   FIX: multiply x and z by 4 (<< 2) at the top of getBiome before
 *   passing them to MapData. The y coordinate doesn't matter for our
 *   2-D map sampling.
 *
 * BIOME MATRIX (CRITICAL FIX #2 — EXACT MATCH WITH map_locator.py):
 *   Previously we used 3 humidity buckets (dry/medium/wet) and an
 *   altitude-adjusted temperature, which produced biomes that did NOT
 *   match the biome_map.png generated by map_locator.py.
 *
 *   Now we use the EXACT same rules as map_locator.py:
 *     • 2 humidity buckets: dry (<128) and wet (≥128).
 *     • Climate zone used DIRECTLY (no altitude temperature adjustment).
 *     • The biome matrix is a 1:1 transcription of biome_rules in
 *       map_locator.py (see buildBiomeMatrix() below).
 *   This makes the in-game biome distribution match the preview image
 *   the user sees in biome_map.png.
 * ─────────────────────────────────────────────────────────────────────────
 */
public class ContinentBiomeSource extends BiomeSource {

    private static final Logger LOGGER = Logger.getLogger("ContinentGen");
    private static final boolean LOG_DEBUG = true;
    private static final int LOG_COUNTER_MAX = 30;
    private static volatile int getBiomeLogCounter = 0;

    // ─── CODEC ────────────────────────────────────────────────────────────
    public static final MapCodec<ContinentBiomeSource> MAP_CODEC =
        RecordCodecBuilder.mapCodec(
            instance -> instance.group(
                RegistryOps.getEntryLookupCodec(RegistryKeys.BIOME),
                Codec.LONG.optionalFieldOf("seed", 0L)
                    .forGetter(ContinentBiomeSource::getSeed),
                Codec.INT.optionalFieldOf("world_size", MapData.DEFAULT_WORLD_SIZE)
                    .forGetter(ContinentBiomeSource::getWorldSize)
            ).apply(instance, instance.stable(ContinentBiomeSource::new))
        );

    public static final Codec<ContinentBiomeSource> CODEC = MAP_CODEC.codec();

    /**
     * Biome matrix: [climateIndex][humidityIndex] -> Biome key.
     *
     * EXACT 1:1 TRANSCRIPTION of biome_rules in map_locator.py:
     *   ARCTIC        + dry → snowy_plains
     *   ARCTIC        + wet → snowy_slopes
     *   SUBARCTIC     + dry → taiga
     *   SUBARCTIC     + wet → snowy_taiga
     *   TEMPERATE     + dry → plains
     *   TEMPERATE     + wet → forest
     *   TROPICAL      + dry → savanna
     *   TROPICAL      + wet → jungle
     *   SUBEQUATORIAL + dry → badlands
     *   SUBEQUATORIAL + wet → mangrove_swamp
     *   EQUATORIAL    + dry → desert
     *   EQUATORIAL    + wet → bamboo_jungle
     *
     * Climate indices match ClimateZone enum ordinal:
     *   0 = ARCTIC, 1 = SUBARCTIC, 2 = TEMPERATE, 3 = TROPICAL,
     *   4 = SUBEQUATORIAL, 5 = EQUATORIAL
     *
     * Humidity indices:
     *   0 = dry (humidity < 128)
     *   1 = wet (humidity ≥ 128)
     *
     * NOTE: snowy_slopes is technically a 3-D biome in vanilla (generates
     * on slopes), but in 1.20.1 it can be placed as a 2-D biome too — it
     * just looks like a snowy hillside. Same for mangrove_swamp (requires
     * water nearby, but generates fine standalone).
     */
    private static final RegistryKey<Biome>[][] BIOME_MATRIX = buildBiomeMatrix();

    private final long seed;
    private final int worldSize;
    private final MapData mapData;
    private final RegistryEntryLookup<Biome> biomeRegistry;
    private final List<RegistryEntry<Biome>> biomeEntries;
    private final Map<RegistryKey<Biome>, RegistryEntry<Biome>> biomeLookupMap;
    private final RegistryEntry<Biome> plainsFallback;

    // Water biome keys
    private static final RegistryKey<Biome> OCEAN_KEY = bikey("ocean");
    private static final RegistryKey<Biome> DEEP_OCEAN_KEY = bikey("deep_ocean");
    private static final RegistryKey<Biome> FROZEN_OCEAN_KEY = bikey("frozen_ocean");
    private static final RegistryKey<Biome> COLD_OCEAN_KEY = bikey("cold_ocean");
    private static final RegistryKey<Biome> RIVER_KEY = bikey("river");
    private static final RegistryKey<Biome> FROZEN_RIVER_KEY = bikey("frozen_river");
    private static final RegistryKey<Biome> SWAMP_KEY = bikey("swamp");
    private static final RegistryKey<Biome> PLAINS_KEY = bikey("plains");

    // ─── Accessors ───────────────────────────────────────────────────────
    public RegistryEntryLookup<Biome> getBiomeRegistry() { return biomeRegistry; }
    public long getSeed() { return seed; }
    public int getWorldSize() { return worldSize; }

    public ContinentBiomeSource(RegistryEntryLookup<Biome> biomeRegistry, long seed, int worldSize) {
        this.seed = seed;
        this.worldSize = worldSize;
        this.biomeRegistry = biomeRegistry;
        this.mapData = MapLoader.getInstance().getMapData();

        this.biomeLookupMap = new HashMap<>();
        this.biomeEntries = new ArrayList<>();

        LOGGER.info("╔══════════════════════════════════════════════════════════════");
        LOGGER.info("║ [ContinentBiomeSrc] Constructor called.");
        LOGGER.info("║   seed=" + seed + "  worldSize=" + worldSize
            + " (half=" + (worldSize/2) + ")");
        LOGGER.info("║   mapsLoaded=" + mapData.isLoaded());
        if (mapData.isLoaded()) {
            LOGGER.info("║   imgSize=" + mapData.getImageWidth() + "x" + mapData.getImageHeight()
                + "  blocksPerPixel=" + (int) mapData.getBlocksPerPixel(worldSize));
        }

        Set<RegistryKey<Biome>> allKeys = new HashSet<>();
        for (RegistryKey<Biome>[] row : BIOME_MATRIX) {
            for (RegistryKey<Biome> key : row) {
                if (key != null) allKeys.add(key);
            }
        }
        allKeys.add(OCEAN_KEY);
        allKeys.add(DEEP_OCEAN_KEY);
        allKeys.add(FROZEN_OCEAN_KEY);
        allKeys.add(COLD_OCEAN_KEY);
        allKeys.add(RIVER_KEY);
        allKeys.add(FROZEN_RIVER_KEY);
        allKeys.add(SWAMP_KEY);
        allKeys.add(PLAINS_KEY);

        int resolved = 0, failed = 0;
        for (RegistryKey<Biome> key : allKeys) {
            RegistryEntry<Biome> entry = resolveBiomeEntry(key);
            if (entry != null) {
                biomeLookupMap.put(key, entry);
                biomeEntries.add(entry);
                resolved++;
            } else {
                LOGGER.severe("║   ✗ FAILED to resolve biome: " + key.getValue());
                failed++;
            }
        }
        LOGGER.info("║ [ContinentBiomeSrc] Resolution: " + resolved + " OK, " + failed + " FAILED");

        RegistryEntry<Biome> plains = biomeLookupMap.get(PLAINS_KEY);
        if (plains == null && !biomeEntries.isEmpty()) {
            plains = biomeEntries.get(0);
        }
        if (plains == null) {
            try {
                plains = BuiltinRegistriesAccess.getBiomeEntry(PLAINS_KEY);
                if (plains != null) {
                    biomeLookupMap.put(PLAINS_KEY, plains);
                    biomeEntries.add(plains);
                }
            } catch (Throwable e) {
                LOGGER.severe("║ [ContinentBiomeSrc] Static builtin registry also failed: " + e);
            }
        }
        this.plainsFallback = plains;
        LOGGER.info("╚══════════════════════════════════════════════════════════════");
    }

    private RegistryEntry<Biome> resolveBiomeEntry(RegistryKey<Biome> key) {
        if (biomeRegistry != null) {
            try {
                RegistryEntry.Reference<Biome> ref = biomeRegistry.getOrThrow(key);
                if (ref != null) return ref;
            } catch (Throwable e) {
                LOGGER.warning("║ [ContinentBiomeSrc] Dynamic lookup failed for "
                    + key.getValue() + ": " + e.getMessage());
            }
        }
        RegistryEntry<Biome> fallback = BuiltinRegistriesAccess.getBiomeEntry(key);
        if (fallback != null) {
            LOGGER.warning("║ [ContinentBiomeSrc] (fallback) " + key.getValue()
                + " via STATIC builtin — may cause -1 on client");
        }
        return fallback;
    }

    @Override
    protected Codec<? extends BiomeSource> getCodec() {
        return CODEC;
    }

    @Override
    protected Stream<RegistryEntry<Biome>> biomeStream() {
        return biomeEntries.stream();
    }

    /**
     * BiomeSource.getBiome is called with QUART-RESOLUTION coordinates
     * (1 unit = 4 blocks). The vanilla BiomeAccess does `pos.getX() >> 2`
     * before calling this. We must shift back to BLOCK coordinates before
     * sampling our PNG map, otherwise every biome lands at 1/4 of the
     * real world position.
     *
     * Biome selection rules now EXACTLY match map_locator.py:
     *   - Climate zone used directly (no altitude temp adjustment).
     *   - 2 humidity buckets (dry <128, wet ≥128).
     */
    @Override
    public RegistryEntry<Biome> getBiome(int x, int y, int z, MultiNoiseUtil.MultiNoiseSampler noise) {
        // Convert biome-resolution coords (1 unit = 4 blocks) to block coords.
        int blockX = x << 2;
        int blockZ = z << 2;

        if (mapData.isLoaded()) {
            // === WATER FEATURES (priority over land) ===
            // Use a smooth oceanNess factor (0..1) so we don't get a hard
            // biome border at the coast — when oceanNess > 0.5 we call it
            // ocean; otherwise it's land/river/lake.
            double oceanNess = mapData.getOceanNess(blockX, blockZ, worldSize);
            if (oceanNess > 0.5) {
                RegistryEntry<Biome> biome = getOceanBiome(blockX, blockZ);
                if (biome != null) return biome;
            }
            if (mapData.isRiver(blockX, blockZ, worldSize)) {
                float temp = mapData.getTemperature(blockX, blockZ, worldSize);
                RegistryEntry<Biome> b = temp < 0.15f ? getEntry(FROZEN_RIVER_KEY) : getEntry(RIVER_KEY);
                if (b != null) return b;
            }
            if (mapData.isLake(blockX, blockZ, worldSize)) {
                float temp = mapData.getTemperature(blockX, blockZ, worldSize);
                RegistryEntry<Biome> b = temp < 0.15f ? getEntry(FROZEN_OCEAN_KEY) : getEntry(SWAMP_KEY);
                if (b != null) return b;
            }

            // === LAND BIOME SELECTION (matches map_locator.py exactly) ===
            // Use ClimateZone DIRECTLY — no altitude-based temperature
            // adjustment. The Python script uses climate zone + humidity
            // bucket only.
            ClimateZone zone = mapData.getClimateZone(blockX, blockZ, worldSize);
            int humidity = mapData.getHumidity(blockX, blockZ, worldSize);

            int climateIdx = zone.ordinal();        // 0..5 matching ClimateZone enum
            int humIdx = (humidity < 128) ? 0 : 1;  // 0=dry, 1=wet

            RegistryKey<Biome> biomeKey = BIOME_MATRIX[climateIdx][humIdx];
            if (biomeKey != null) {
                RegistryEntry<Biome> entry = getEntry(biomeKey);
                if (entry != null) return entry;
            }
        } else {
            if (LOG_DEBUG && getBiomeLogCounter < 3) {
                getBiomeLogCounter++;
                LOGGER.warning("[getBiome] MAPS NOT LOADED! (" + blockX + "," + y + "," + blockZ + ")");
            }
        }

        if (plainsFallback != null) return plainsFallback;
        if (!biomeEntries.isEmpty()) return biomeEntries.get(0);
        LOGGER.severe("[getBiome] *** NO BIOME AVAILABLE! ***");
        return null;
    }

    private RegistryEntry<Biome> getOceanBiome(int x, int z) {
        boolean deep = mapData.isDeepOcean(x, z, worldSize);
        float temp = mapData.getTemperature(x, z, worldSize);
        if (deep) {
            if (temp < 0.15f) return getEntry(FROZEN_OCEAN_KEY);
            return getEntry(DEEP_OCEAN_KEY);
        }
        if (temp < 0.15f) return getEntry(FROZEN_OCEAN_KEY);
        if (temp < 0.35f) return getEntry(COLD_OCEAN_KEY);
        return getEntry(OCEAN_KEY);
    }

    private RegistryEntry<Biome> getEntry(RegistryKey<Biome> key) {
        RegistryEntry<Biome> entry = biomeLookupMap.get(key);
        if (entry == null) return plainsFallback;
        return entry;
    }

    // ======================== Helpers ========================

    /**
     * Build the biome matrix that EXACTLY matches biome_rules in
     * map_locator.py. See class javadoc for the full table.
     *
     * Row index = ClimateZone.ordinal() (0..5).
     * Column index = humidity bucket (0=dry, 1=wet).
     */
    private static RegistryKey<Biome>[][] buildBiomeMatrix() {
        @SuppressWarnings("unchecked")
        RegistryKey<Biome>[][] matrix = new RegistryKey[6][2];
        // 0 = ARCTIC
        matrix[0][0] = bikey("snowy_plains");   matrix[0][1] = bikey("snowy_slopes");
        // 1 = SUBARCTIC
        matrix[1][0] = bikey("taiga");           matrix[1][1] = bikey("snowy_taiga");
        // 2 = TEMPERATE
        matrix[2][0] = bikey("plains");          matrix[2][1] = bikey("forest");
        // 3 = TROPICAL
        matrix[3][0] = bikey("savanna");         matrix[3][1] = bikey("jungle");
        // 4 = SUBEQUATORIAL
        matrix[4][0] = bikey("badlands");        matrix[4][1] = bikey("mangrove_swamp");
        // 5 = EQUATORIAL
        matrix[5][0] = bikey("desert");          matrix[5][1] = bikey("bamboo_jungle");
        return matrix;
    }

    private static RegistryKey<Biome> bikey(String path) {
        return RegistryKey.of(RegistryKeys.BIOME, Identifier.of("minecraft", path));
    }
}
